services:
  postgres:
    image: postgres:16-alpine
    container_name: vault-postgres
    environment:
      POSTGRES_DB: vault
      POSTGRES_USER: vault_user
      POSTGRES_PASSWORD: vault_password
    ports:
      - "5432:5432"
    volumes:
      - vault-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vault_user" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  vault-data:
